"""Template-based ASHA and Clinical Referral Summary generator.

Follows Section 13.6 and Prompt 5 specifications:
- Pure deterministic template logic (no LLM hallucination risk)
- Formats structured referral text suitable for copying, WhatsApp sharing, or PHC handoff
- Explicitly disclaims clinical diagnosis
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from ai.schemas import Language, RiskLevel, TriageResult

# Static language headers
SUMMARY_TEMPLATES = {
    Language.EN: {
        "title": "=== SWASTHASATHI HEALTHCARE REFERRAL SUMMARY ===",
        "date": "Date & Time",
        "lang": "Session Language",
        "concern": "Main Concern / Reported Symptoms",
        "patient": "Patient Group",
        "answers": "Key Follow-Up Answers",
        "red_flags": "Red Flags Detected",
        "risk_level": "Triage Risk Level",
        "action": "Recommended Next Step",
        "first_aid": "First-Aid Actions Advised",
        "warnings": "Warning Signs to Watch For",
        "source": "Audit Source",
        "disclaimer": "NOTE: Generated by SwasthaSathi automated decision support for ASHA/caregiver guidance. This is NOT a clinical diagnosis and does not replace evaluation by a qualified medical professional.",
    },
    Language.HI: {
        "title": "=== स्वास्थ्यसाथी स्वास्थ्य रेफरल सारांश ===",
        "date": "दिनांक व समय",
        "lang": "भाषा",
        "concern": "मुख्य समस्या व लक्षण",
        "patient": "मरीज़ वर्ग",
        "answers": "जरूरी सवालों के जवाब",
        "red_flags": "गंभीर खतरे के संकेत",
        "risk_level": "जांच का जोखिम स्तर",
        "action": "सुझाया गया अगला कदम",
        "first_aid": "दी गई प्राथमिक उपचार सलाह",
        "warnings": "सावधानी / चेतावनी संकेत",
        "source": "निर्णय का आधार",
        "disclaimer": "सूचना: यह स्वास्थ्यसाथी स्वचालित निर्णय सहायता प्रणाली द्वारा आशा कार्यकर्ता / स्वास्थ्य केंद्र के लिए तैयार किया गया है। यह कोई डॉक्टरी जांच (निदान) नहीं है।",
    },
    Language.MR: {
        "title": "=== स्वास्थ्यसाथी आरोग्य रेफरल सारांश ===",
        "date": "तारीख आणि वेळ",
        "lang": "भाषा",
        "concern": "मुख्य तक्रार आणि लक्षणे",
        "patient": "रुग्ण वर्ग",
        "answers": "महत्त्वाच्या प्रश्नांची उत्तरे",
        "red_flags": "धोक्याची चिन्हे",
        "risk_level": "तपासणीचा जोखीम स्तर",
        "action": "पुढील शिफारस केलेले पाऊल",
        "first_aid": "दिलेला प्रथमोपचार सल्ला",
        "warnings": "लक्षात ठेवण्याची धोक्याची चिन्हे",
        "source": "निर्णयाचा स्रोत",
        "disclaimer": "सूचना: हा सारांश स्वास्थ्यसाथी निर्णय सहाय्य प्रणालीद्वारे आशा ताई / आरोग्य केंद्रासाठी तयार करण्यात आला आहे. हे कोणतेही वैद्यकीय निदान नाही.",
    },
}


def generate_asha_summary(
    result: TriageResult,
    raw_symptom_text: str = "",
    follow_up_answers: Optional[list[dict[str, str]]] = None,
    language: Language = Language.EN,
) -> str:
    """Generate structured, formatted text summary for ASHA handoff or PHC doctor."""
    t = SUMMARY_TEMPLATES.get(language, SUMMARY_TEMPLATES[Language.EN])
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Format symptoms
    symptoms_list = ", ".join(s.name for s in result.symptoms) if result.symptoms else raw_symptom_text or "Not specified"
    patient_group = result.patient_context.age_group or "General / Unspecified"

    # Risk level badge representation
    if result.risk_level == RiskLevel.EMERGENCY:
        risk_str = "EMERGENCY (आपातकाल / तातडीने रुग्णालय)"
    elif result.risk_level == RiskLevel.VISIT_PHC:
        urgency = result.urgency_label.value if result.urgency_label else "TODAY"
        risk_str = f"VISIT PHC ({urgency})"
    else:
        risk_str = "HOME CARE & OBSERVATION"

    lines = [
        t["title"],
        f"{t['date']}: {now_str}",
        f"{t['lang']}: {language.value.upper()}",
        f"{t['patient']}: {patient_group}",
        f"{t['concern']}: {symptoms_list}",
    ]

    # Follow-up answers if present
    if follow_up_answers:
        lines.append(f"\n{t['answers']}:")
        for ans in follow_up_answers:
            q_text = ans.get("question", "")
            a_val = ans.get("answer", "")
            lines.append(f"  • {q_text}: {a_val}")

    # Red flags
    if result.red_flags:
        rf_ids = ", ".join(rf.rule_id for rf in result.red_flags)
        lines.append(f"\n{t['red_flags']}: {rf_ids}")

    # Core assessment
    lines.append(f"\n{t['risk_level']}: {risk_str}")
    lines.append(f"{t['action']}: {result.recommended_action}")

    # First-aid IDs
    if result.first_aid_ids:
        lines.append(f"{t['first_aid']}: {', '.join(result.first_aid_ids)}")

    # Warning sign IDs
    if result.warning_signs_to_return:
        lines.append(f"{t['warnings']}: {', '.join(result.warning_signs_to_return)}")

    lines.append(f"{t['source']}: {result.risk_source.value.upper()}")
    lines.append("\n" + "-" * 50)
    lines.append(t["disclaimer"])
    lines.append("=" * 50)

    return "\n".join(lines)
